apps/teams/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = "teams"

urlpatterns = [
    path("", views.manage_teams, name="teams_home"),
    path("manage/", views.manage_teams, name="manage_teams"),
    path("manage/<path:path>", views.manage_teams, name="manage_teams"),
    # invitation acceptance views
    path("invitation/<slug:invitation_id>/", views.accept_invitation, name="accept_invitation"),
    path("invitation/<slug:invitation_id>/signup/", views.SignupAfterInvite.as_view(), name="signup_after_invite"),
]

team_urlpatterns = (
    [
        # team management views
        path("", views.manage_team, name="manage_team"),
        path("members/<int:membership_id>/", views.team_membership_details, name="team_membership_details"),
        path("members/<int:membership_id>/remove/", views.remove_team_membership, name="remove_team_membership"),
        path("invite/<slug:invitation_id>/", views.resend_invitation, name="resend_invitation"),
    ],
    "single_team",
)


# DRF config for API views (required for React Teams, implementation, optional otherwise)
router = routers.DefaultRouter()
router.register("api/teams", views.TeamViewSet)
urlpatterns += router.urls

single_team_router = routers.DefaultRouter()
single_team_router.register("api/invitations", views.InvitationViewSet)
team_urlpatterns[0].extend(single_team_router.urls)

time_sheet_saas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.api.v2.views import PagesAPIViewSet
from wagtail.contrib.sitemaps import Sitemap
from wagtail.documents import urls as wagtaildocs_urls

from apps.subscriptions.urls import team_urlpatterns as subscriptions_team_urls
from apps.teams.urls import team_urlpatterns as single_team_urls
from apps.web.sitemaps import StaticViewSitemap
from apps.web.urls import team_urlpatterns as web_team_urls

PagesAPIViewSet.schema = None  # hacky workaround for https://github.com/wagtail/wagtail/issues/8583

sitemaps = {
    "static": StaticViewSitemap(),
    "wagtail": Sitemap(),
}

# urls that are unique to using a team should go here
team_urlpatterns = [
    path("", include(web_team_urls)),
    path("subscription/", include(subscriptions_team_urls)),
    path("team/", include(single_team_urls)),
    path("example/", include("apps.teams_example.urls")),
]

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # redirect Django admin login to main login page
    path("admin/login/", RedirectView.as_view(pattern_name="account_login")),
    path("admin/", admin.site.urls),
    path("dashboard/", include("apps.dashboard.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap"),
    path("a/<slug:team_slug>/", include(team_urlpatterns)),
    path("accounts/", include("allauth.urls")),
    path("users/", include("apps.users.urls")),
    path("subscriptions/", include("apps.subscriptions.urls")),
    path("ecommerce/", include("apps.ecommerce.urls")),
    path("teams/", include("apps.teams.urls")),
    path("", include("apps.web.urls")),
    path("pegasus/", include("pegasus.apps.examples.urls")),
    path("pegasus/employees/", include("pegasus.apps.employees.urls")),
    path("support/", include("apps.support.urls")),
    path("celery-progress/", include("celery_progress.urls")),
    # auth API
    path("api/auth/", include("apps.authentication.urls")),
    # API docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI - you may wish to remove one of these depending on your preference
    path("api/schema/swagger-ui/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # djstripe urls - for webhooks
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    # hijack urls for impersonation
    path("hijack/", include("hijack.urls", namespace="hijack")),
    # wagtail config
    # redirect Wagtail admin login to main login page
    path("cms/login/", RedirectView.as_view(pattern_name="account_login")),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("content/", include(wagtail_urls)),
    path("ai_images/", include("apps.ai_images.urls")),
    path("chat/", include("apps.chat.urls")),
    path("group-chat/", include("apps.group_chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/teams/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from apps.users.forms import TurnstileSignupForm

from .helpers import create_default_team_for_user
from .models import Invitation, Membership


class TeamSignupForm(TurnstileSignupForm):
    invitation_id = forms.CharField(widget=forms.HiddenInput(), required=False)
    team_name = forms.CharField(
        label=_("Team Name (Optional)"),
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": _("Team Name (Optional)")}),
        required=False,
    )
    terms_agreement = forms.BooleanField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # blank out overly-verbose help text
        self.fields["password1"].help_text = ""
        link = '<a class="link" href={} target="_blank">{}</a>'.format(
            reverse("web:terms"),
            _("Terms and Conditions"),
        )
        self.fields["terms_agreement"].label = mark_safe(_("I agree to the {terms_link}").format(terms_link=link))

    def clean(self):
        cleaned_data = super().clean()
        if not self.errors:
            self._clean_team_name(cleaned_data)
            self._clean_invitation_email(cleaned_data)
        return cleaned_data

    def _clean_team_name(self, cleaned_data):
        team_name = cleaned_data.get("team_name")
        invitation_id = cleaned_data.get("invitation_id")
        # if invitation is not set then team name is required
        if not invitation_id and not team_name:
            email = cleaned_data.get("email")
            if email is not None:
                team_name = f"{email.split('@')[0]}"
        elif invitation_id:
            assert not team_name

        cleaned_data["team_name"] = team_name

    def _clean_invitation_email(self, cleaned_data):
        invitation_id = cleaned_data.get("invitation_id")
        if invitation_id:
            try:
                invite = Invitation.objects.get(id=invitation_id)
            except (Invitation.DoesNotExist, ValidationError):
                # ValidationError is raised if the ID isn't a valid UUID, which should be treated the same
                # as not found
                raise forms.ValidationError(
                    _(
                        "That invitation could not be found. "
                        "Please double check your invitation link or sign in to continue."
                    )
                )

            if invite.is_accepted:
                raise forms.ValidationError(
                    _(
                        "It looks like that invitation link has expired. "
                        "Please request a new invitation or sign in to continue."
                    )
                )

            email = cleaned_data.get("email")  # this is always lowercase via form validation
            if invite.email.lower() != email:
                raise forms.ValidationError(
                    _("You must sign up with the email address that the invitation was sent to.")
                )

    def save(self, request):
        invitation_id = self.cleaned_data["invitation_id"]
        team_name = self.cleaned_data["team_name"]
        user = super().save(request)

        # if the account already exists, the super().save call is empty, so don't do any post-processing
        if not user:
            return

        if not invitation_id:
            create_default_team_for_user(user, team_name)

        return user


class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ("role",)

apps/teams/views/api_views.py
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from drf_spectacular.utils import extend_schema, extend_schema_view
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied
from rest_framework.exceptions import ValidationError as DRFValidationError

from apps.api.permissions import IsAuthenticatedOrHasUserAPIKey

from ..invitations import send_invitation
from ..models import Invitation, Team
from ..permissions import TeamAccessPermissions, TeamModelAccessPermissions
from ..roles import is_admin, is_member
from ..serializers import InvitationSerializer, TeamSerializer


@extend_schema_view(
    create=extend_schema(operation_id="teams_create"),
    list=extend_schema(operation_id="teams_list"),
    retrieve=extend_schema(operation_id="teams_retrieve"),
    update=extend_schema(operation_id="teams_update"),
    partial_update=extend_schema(operation_id="teams_partial_update"),
    destroy=extend_schema(operation_id="teams_destroy"),
)
class TeamViewSet(viewsets.ModelViewSet):
    queryset = Team.objects.all()
    serializer_class = TeamSerializer
    permission_classes = (IsAuthenticatedOrHasUserAPIKey, TeamAccessPermissions)

    def get_queryset(self):
        # filter queryset based on logged in user
        return self.request.user.teams.order_by("name")

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        team = serializer.save()
        team.members.add(self.request.user, through_defaults={"role": "admin"})


@extend_schema(tags=["teams"])
@extend_schema_view(
    create=extend_schema(operation_id="invitations_create"),
    list=extend_schema(operation_id="invitations_list"),
    retrieve=extend_schema(operation_id="invitations_retrieve"),
    update=extend_schema(operation_id="invitations_update"),
    partial_update=extend_schema(operation_id="invitations_partial_update"),
    destroy=extend_schema(operation_id="invitations_destroy"),
)
class InvitationViewSet(viewsets.ModelViewSet):
    queryset = Invitation.objects.all()
    serializer_class = InvitationSerializer
    permission_classes = (IsAuthenticatedOrHasUserAPIKey, TeamModelAccessPermissions)

    @property
    def team(self):
        team = get_object_or_404(Team, slug=self.kwargs["team_slug"])
        if is_member(self.request.user, team):
            return team
        else:
            raise PermissionDenied()

    def _ensure_team_match(self, team):
        if team != self.team:
            raise DRFValidationError("Team set in invitation must match URL")

    def _ensure_no_pending_invite(self, team, email):
        if Invitation.objects.filter(team=team, email=email, is_accepted=False):
            raise DRFValidationError(
                {
                    # this mimics the same validation format used by the serializer so it can work easily on the front end.
                    "email": [
                        _(
                            'There is already a pending invitation for {}. You can resend it by clicking "Resend Invitation".'
                        ).format(email)
                    ]
                }
            )

    def get_queryset(self):
        # filter queryset based on logged in user and team
        return self.queryset.filter(team=self.team)

    def perform_create(self, serializer):
        # ensure logged in user is set on the model during creation
        # and can access the underlying team
        team = serializer.validated_data["team"]
        self._ensure_team_match(team)
        self._ensure_no_pending_invite(team, serializer.validated_data["email"])

        # unfortunately, the permissions class doesn't handle creation well
        # https://www.django-rest-framework.org/api-guide/permissions/#limitations-of-object-level-permissions
        if not is_admin(self.request.user, team):
            raise PermissionDenied()

        invitation = serializer.save(invited_by=self.request.user)
        send_invitation(invitation)

apps/teams/views/invitation_views.py
from allauth.account.views import SignupView
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from apps.users.models import CustomUser

from ..invitations import clear_invite_from_session, process_invitation
from ..models import Invitation
from ..roles import is_member


def accept_invitation(request, invitation_id):
    invitation = get_object_or_404(Invitation, id=invitation_id)
    if not invitation.is_accepted:
        # set invitation in the session in case needed later - e.g. to redirect after login
        request.session["invitation_id"] = invitation_id
    else:
        clear_invite_from_session(request)
    if request.user.is_authenticated and is_member(request.user, invitation.team):
        messages.info(
            request,
            _("It looks like you're already a member of {team}. You've been redirected.").format(
                team=invitation.team.name
            ),
        )
        return HttpResponseRedirect(reverse("web_team:home", args=[invitation.team.slug]))

    if request.method == "POST":
        # accept invitation workflow
        if not request.user.is_authenticated:
            messages.error(request, _("Please log in again to accept your invitation."))
            return HttpResponseRedirect(reverse("account_login"))
        else:
            if invitation.is_accepted:
                messages.error(request, _("Sorry, it looks like that invitation link has expired."))
                return HttpResponseRedirect(reverse("web:home"))
            else:
                process_invitation(invitation, request.user)
                clear_invite_from_session(request)
                messages.success(request, _("You successfully joined {}").format(invitation.team.name))
                return HttpResponseRedirect(reverse("web_team:home", args=[invitation.team.slug]))

    account_exists = CustomUser.objects.filter(email=invitation.email).exists()
    return render(
        request,
        "teams/accept_invite.html",
        {
            "invitation": invitation,
            "account_exists": account_exists,
        },
    )


class SignupAfterInvite(SignupView):
    @cached_property
    def invitation(self) -> Invitation:
        from ..models import Invitation

        invitation_id = self.kwargs["invitation_id"]

        invitation = get_object_or_404(Invitation, id=invitation_id)
        if invitation.is_accepted:
            messages.error(self.request, _("Sorry, it looks like that invitation link has expired."))
            raise Http404
        return invitation

    def get_initial(self):
        initial = super().get_initial()
        if self.invitation:
            initial["team_name"] = self.invitation.team.name
            initial["email"] = self.invitation.email
        return initial

    def get_context_data(self, **kwargs):
        context = super(SignupAfterInvite, self).get_context_data(**kwargs)
        if self.invitation:
            context["invitation"] = self.invitation
        return context

apps/teams/views/manage_team_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_POST

from apps.users.serializers import CustomUserSerializer

from ..api_url_helpers import get_team_api_url_templates
from ..decorators import login_and_team_required, team_admin_required
from ..invitations import send_invitation
from ..models import Invitation
from ..serializers import TeamSerializer


@login_required
def manage_teams(request, path=""):
    return render(
        request,
        "teams/teams.html",
        {
            "api_urls": get_team_api_url_templates(),
            "user_json": CustomUserSerializer(request.user).data,
            "page_title": _("Manage Teams"),
        },
    )


@login_and_team_required
def manage_team(request, team_slug):
    team = request.team
    return render(
        request,
        "teams/manage_team_react.html",
        {
            "team": team,
            "team_json": TeamSerializer(team, context={"request": request}).data,
            "user_json": CustomUserSerializer(request.user).data,
            "active_tab": "manage-team",
            "api_urls": get_team_api_url_templates(),
        },
    )


@team_admin_required
@require_POST
def resend_invitation(request, team_slug, invitation_id):
    invitation = get_object_or_404(Invitation, team=request.team, id=invitation_id)
    send_invitation(invitation)
    return HttpResponse("Ok")

templates/teams/accept_invite.html
{% extends "web/base.html" %}
{% load static %}
{% load i18n %}
{% block body %}
<section class="mt-7 section">
  <div class= "container">
    <div class="pg-columns pg-align-items-center">
      <div class="pg-column-one-third">
        <img class="img-fluid" src="{% static 'images/undraw/undraw_lighthouse.svg' %}" alt="{% translate "Welcome!" %}">
      </div>
      <div class="pg-column">
        {% if not invitation.is_accepted %}
          <h1 class="pg-title">{% translate "Accept Invitation?" %}</h1>
          <h2 class="pg-subtitle">
            {% blocktranslate with team_name=invitation.team.name by=invitation.invited_by.get_display_name %}
            You've been invited to join {{ team_name }} by {{ by }}.
            {% endblocktranslate %}
          </h2>
          {% if request.user.is_authenticated %}
            <form method="post">
              {% csrf_token %}
              {% if request.user.email == invitation.email %}
                <input type="submit" class="pg-button-primary" value="Accept Invitation"/>
              {% else %}
                <p >
                  {% blocktranslate with invite_email=invitation.email user_email=request.user.email  %}
                  This invitation was sent to {{ invite_email }} but you're logged in as {{ user_email }}.
                  What would you like to do?
                  {% endblocktranslate %}
                </p>
                <p class="buttons my-3">
                  <input type="submit" class="pg-button-primary" value="Accept as {{ request.user.email }}"/>
                  <a class="pg-button-secondary" href="{% url 'account_logout' %}?invitation_id={{ invitation.id }}">
                    {% translate "Sign out" %}
                  </a>
                </p>
              {% endif %}
            </form>
          {% else %}
            <p class="buttons">
              {% if account_exists %}
                <a class="pg-button-primary" href="{% url 'account_login' %}?next={% url 'teams:accept_invitation' invitation.id %}">
                  {% translate "Log in to Accept" %}
                </a>
              {% else %}
                <a class="pg-button-primary" href="{% url 'teams:signup_after_invite' invitation.id %}">
                  {% translate "Create Account to Accept" %}
                </a>
              {% endif %}
            </p>
          {% endif %}
        {% else %}
          <p class="pg-subtitle">
            {% translate "Sorry, it looks like that invitation has already been accepted or expired." %}
          </p>
          <p>
            {% translate "If you think this is a mistake, ask your team administrator to invite you again!" %}
          </p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/teams/manage_team_react.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% block app %}
<div id="manage-team-content"></div>
{{ user_json|json_script:'user-details' }}
{{ team_json|json_script:'team' }}
{{ api_urls|json_script:'api-urls' }}
{{ server_url|json_script:'server-url' }}
{% endblock %}
{% block page_js %}
<script src="{% static 'js/edit-team-bundle.js' %}" defer></script>
{% endblock %}

templates/teams/team_membership_details.html
{% extends "web/app/app_base.html" %}
{% load i18n %}
{% load static %}
{% load form_tags %}
{% block app %}
<nav aria-label="breadcrumbs">
  <ol class="pg-breadcrumbs">
    <li class=""><a href="{% url 'single_team:manage_team' request.team.slug %}">{{ request.team.name }}</a></li>
    <li class="pg-breadcrumb-active" aria-current="page">{{ membership.user.get_display_name }}</li>
  </ol>
</nav>
<section class="app-card">
  <div class="pg-columns">
    <div id="profile-picture" class="pg-column-one-quarter">
      <div>
        <img class="avatar" src="{{ membership.user.avatar_url }}">
        <div class="pg-text-centered">{{ membership.user.get_display_name }}</div>
      </div>
    </div>
    <div class="pg-column">
      <div>
        <div class="pg-label">{% translate "Email" %}</div>
        <div class="pg-text-muted">{{ membership.user.email }}</div>
      </div>
      <div class="mt-2">
        <div class="pg-label">{% translate "Date Joined" %}</div>
        <div class="pg-text-muted">{{ membership.created_at }}</div>
      </div>
      <form class="mt-2" method="post">
        {% csrf_token %}
        {% render_form_fields membership_form %}
        {% if not editing_self %}
          <div class="mt-2">
            <input type="submit" class="pg-button-secondary" value="{% translate 'Update Role' %}">
          </div>
        {% else %}
          <p class="pg-help">{% translate "You are not allowed to modify your own role." %}</p>
        {% endif %}
        <hr class="my-2">
        <label for="remove-member-modal" class="pg-button-danger modal-button">
          {% if editing_self %}
            {% translate 'Leave Team' %}
          {% else %}
            {% translate 'Remove from Team' %}
          {% endif %}
        </label>
      </form>
    </div>
  </div>
</section>
{% include 'teams/components/remove_member_modal.html' %}
{% endblock %}

templates/teams/teams.html
{% extends "web/app/app_base.html" %}
{% load static %}
{% load i18n %}
{% block app %}
  <div id="team-content"></div>
  {{ api_urls|json_script:'api-urls' }}
  {{ user_json|json_script:'user-details' }}
{% endblock %}
{% block page_js %}
{# NOTE: the rest framework imports must precede the react bundle #}
<script>
    // initialize any page specific stuff here
    // static files that are used by the page javascript.
    const STATIC_FILES = {
        'undraw_team': "{% static 'images/undraw/undraw_team.svg' %}",
    };
    const SERVER_URL_BASE = "{{ server_url }}";
    const urlBase = "{% url 'teams:manage_teams' %}";
</script>
<script src="{% static 'js/teams-bundle.js' %}" defer></script>
{% endblock %}